# Usa uma única variável para a conexão completa
spring.datasource.url=${DB_URL}

# Configurações de sobrevivência do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect