# Nome da nossa aplicação
spring.application.name=jf-details-api

# Configurações do Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:jfdetailsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Permitir que o Spring crie as tabelas automaticamente baseado nas nossas classes @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar o painel visual do banco de dados no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console